from sites.common import cpu_env_list

# Shared account string for all calcua clusters (vaughan, leibniz, breniac)
_acc = '-A ap_calcua_staff'
_gpu_resources = [{'name': 'gpu', 'options': ['--gpus-per-node={num_gpus}']}]

# UA (calcua) - Vaughan, Leibniz, Breniac (all tier-2)
systems = [
    {
        'name': 'vaughan',
        'descr': 'VSC Tier-2 Vaughan',
        'hostnames': ['.*vaughan'],
        'modules_system': 'lmod',
        'partitions': [
            {
                'name': 'login',
                'scheduler': 'local',
                'modules': [],
                'access': [],
                'environs': ['standard'],
                'descr': 'tests on the login node (no job)',
                'max_jobs': 10,
                'launcher': 'local',
                'features': ['login'],
                'extras': {'num_cpus': 32},
            },
            {
                'name': 'default',
                'scheduler': 'slurm',
                'modules': [],
                'access': [_acc],
                'environs': cpu_env_list,
                'descr': 'default-node jobs',
                'max_jobs': 20,
                'launcher': 'local',
                'features': ['cpu', 'default'],
                'extras': {'num_cpus': 64},
            },
            {
                'name': 'zen2',
                'scheduler': 'slurm',
                'modules': [],
                'access': [_acc, '-p zen2'],
                'environs': cpu_env_list,
                'descr': 'zen2 nodes',
                'max_jobs': 20,
                'launcher': 'local',
                'features': ['cpu'],
                'extras': {'num_cpus': 64},
            },
            {
                'name': 'zen3',
                'scheduler': 'slurm',
                'modules': [],
                'access': [_acc, '-p zen3'],
                'environs': cpu_env_list,
                'descr': 'zen3 nodes',
                'max_jobs': 20,
                'launcher': 'local',
                'features': ['cpu'],
                'extras': {'num_cpus': 64},
            },
            {
                'name': 'zen3_512',
                'scheduler': 'slurm',
                'modules': [],
                'access': [_acc, '-p zen3_512'],
                'environs': cpu_env_list,
                'descr': 'zen3 nodes, 512GB memory',
                'max_jobs': 20,
                'launcher': 'local',
                'features': ['cpu'],
                'extras': {'num_cpus': 64},
            },
            {
                'name': 'nvidia',
                'scheduler': 'slurm',
                'modules': [],
                'access': [_acc, '-p ampere_gpu'],
                'environs': ['CUDA', 'standard'],
                'descr': 'Nvidia ampere node',
                'max_jobs': 10,
                'launcher': 'local',
                'resources': _gpu_resources,
                'features': ['gpu', 'nvidia'],
                'extras': {'num_cpus': 64, 'num_gpus': 4},
            },
            {
                'name': 'amd',
                'scheduler': 'slurm',
                'modules': [],
                'access': [_acc, '-p arcturus_gpu'],
                'environs': ['standard'],
                'descr': 'AMD GPU node',
                'max_jobs': 10,
                'launcher': 'local',
                'resources': _gpu_resources,
                'features': ['gpu', 'amd'],
                'extras': {'num_cpus': 64, 'num_gpus': 2},
            },
        ]
    },
    {
        'name': 'leibniz',
        'descr': 'VSC Tier-2 Leibniz',
        'hostnames': ['.*leibniz'],
        'modules_system': 'lmod',
        'partitions': [
            {
                'name': 'login',
                'scheduler': 'local',
                'modules': [],
                'access': [],
                'environs': ['standard'],
                'descr': 'tests on the login node (no job)',
                'max_jobs': 10,
                'launcher': 'local',
                'features': ['login'],
                'extras': {'num_cpus': 56},
            },
            {
                'name': 'default',
                'scheduler': 'slurm',
                'modules': [],
                'access': [_acc],
                'environs': cpu_env_list,
                'descr': 'default-node jobs',
                'max_jobs': 20,
                'launcher': 'local',
                'features': ['cpu', 'default'],
                'extras': {'num_cpus': 28},
            },
            {
                'name': 'broadwell',
                'scheduler': 'slurm',
                'modules': [],
                'access': [_acc, '-p broadwell'],
                'environs': cpu_env_list,
                'descr': 'broadwell nodes',
                'max_jobs': 20,
                'launcher': 'local',
                'features': ['cpu'],
                'extras': {'num_cpus': 28},
            },
            {
                'name': 'broadwell_256',
                'scheduler': 'slurm',
                'modules': [],
                'access': [_acc, '-p broadwell_256'],
                'environs': cpu_env_list,
                'descr': 'broadwell nodes, 256GB memory',
                'max_jobs': 20,
                'launcher': 'local',
                'features': ['cpu'],
                'extras': {'num_cpus': 28},
            },
            {
                'name': 'nvidia',
                'scheduler': 'slurm',
                'modules': [],
                'access': [_acc, '-p pascal_gpu'],
                'environs': ['CUDA', 'standard'],
                'descr': 'Nvidia pascal nodes',
                'max_jobs': 10,
                'launcher': 'local',
                'resources': _gpu_resources,
                'features': ['gpu', 'nvidia', 'deprecated'],
                'extras': {'num_cpus': 28, 'num_gpus': 2},
            },
        ]
    },
    {
        'name': 'breniac',
        'descr': 'VSC Tier-2 Breniac',
        'hostnames': ['.*breniac'],
        'modules_system': 'lmod',
        'partitions': [
            {
                'name': 'login',
                'scheduler': 'local',
                'modules': [],
                'access': [],
                'environs': ['standard'],
                'descr': 'tests on the login node (no job)',
                'max_jobs': 10,
                'launcher': 'local',
                'features': ['login'],
                'extras': {'num_cpus': 28},
            },
            {
                'name': 'default',
                'scheduler': 'slurm',
                'modules': [],
                'access': [_acc],
                'environs': cpu_env_list,
                'descr': 'default-node jobs',
                'max_jobs': 20,
                'launcher': 'local',
                'features': ['cpu', 'default'],
                'extras': {'num_cpus': 28},
            },
            {
                'name': 'skylake',
                'scheduler': 'slurm',
                'modules': [],
                'access': [_acc, '-p skylake'],
                'environs': cpu_env_list,
                'descr': 'skylake nodes',
                'max_jobs': 20,
                'launcher': 'local',
                'features': ['cpu'],
                'extras': {'num_cpus': 28},
            },
        ]
    },
]
